# Site settings
title: "theblog"
email: me@fffabs.com
description: > # this means to ignore newlines until "baseurl:"
 vishnu &copy 2017 - Lets make something!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vishnu1991.github.io" # the base hostname & protocol for your site
twitter_username: v2s2c
github_username:  vishnu1991

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: rouge

# Pagination
paginate: 10
paginate_path: "blog/page/:num/"

# Minification
sass:
  style: compressed
